name: dart_imagehash
version: 2.0.0
description: "A library for computing perceptual image hashes in Dart."
homepage: https://github.com/vaibhavhrt/dart_imagehash
repository: https://github.com/vaibhavhrt/dart_imagehash
topics:
  - image
  - hash
  - imagehash
  - perceptual-hashing
  - image-comparison

environment:
  sdk: ^3.7.2

dependencies:
  collection: ^1.19.1
  image: ^4.5.4

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
